<?php $this->display('header.phtml'); ?>
<!-- Page Content -->
<div class="container">
  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">公司简介</h1>
      <ol class="breadcrumb">
        <li><a href="/">主页</a> </li>
        <li class="active">公司简介</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <!-- Intro Content -->
  <div class="row">
    <div class="col-md-6"> <img class="img-responsive" src="/img/entrance.jpg" alt="" /> </div>
    <div class="col-md-6">
      <p>皓华电子有限公司成立于1993 年是一家专业生产陶瓷、安规电容，代理销售电子元器件的厂商，公司员工近210 人，其中有多名硕士、本科学历的技术和管 理人才。</p>
      <p>我们历经多年海内外市场磨练，已形成多支超强能力的业务团队，是一支具有专业化知识，多技能功底的队伍。早在2000 年公司引入ERP 管理系统，给公司带来极大便利，同时对于资料、资源的保护、延续，公司可持续发展提供了可靠的保障。（关系企业：厚德电子，上海皓厚电子）</p>
      <p>公司自成立以来，锐意进取，不断创新，现已在同行业树立了良好的口碑与信誉，品质与服务是我们一贯坚持的宗旨。为拓展海外市场，我们成立了皓华电子科技公司、皓华电子科技（香港）有限公司，为加大对华东市场的开发力度，我们成立了苏州分公司、合肥分公司，为进军西部市场，我们成立了成都分公司。公司现有大量的优质客户资源，其中不乏世界五百强、国内外知名企业客户。</p>
      <p>为使公司业绩在2015年更上一个新台阶，根据国家对产业的政策调整方向和行业发展预测，公司对今年的发展方向及时微调，加大了对部分产品的推广力度，相信经过公司员工的共同努力，皓华前景一片光明。</p>
    </div>
  </div>
  <!-- /.row -->
  <!-- Products -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">销售品牌</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/aem.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/americanbrightled.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/avx.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/bm.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/bussmann.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/conquer.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/everlight.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/hec.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/hirose.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/holystone.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/jovin.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/kyocera.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/littelfuse.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/nichicon.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/panasonic.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/samsung.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/t-yuden.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/vendor/yageo.gif" alt="" /> </div>
  </div>
  <!-- Our Customers -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">主要合作伙伴</h2>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/benq.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/chiffo.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/emerson_network_power.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/osram.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/primax.gif" alt="" /> </div>
    <div class="col-md-2 col-sm-4 col-xs-6"> <img class="img-responsive thumbnail" src="/img/customer/sanyo.gif" alt="" /> </div>
  </div>
  <!-- /.row -->
  <?php $this->display('copyright.phtml'); ?>
</div><!-- /.container -->
<?php $this->display('footer.phtml'); ?>