<?php $this->display('header.phtml'); ?>
<!-- Page Content -->
<div class="container">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active"> <img src="http://placehold.it/900x500" alt="" />
        <div class="carousel-caption"> .12313.. </div>
      </div>
      <div class="item"> <img src="http://placehold.it/900x500" alt="" />
        <div class="carousel-caption"> .44444444.. </div>
      </div>
      <div class="item"> <img src="http://placehold.it/900x500" alt="" />
        <div class="carousel-caption"> .44444444.. </div>
      </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="sr-only">Next</span> </a> </div>
  <!-- /.carousel -->
  <!-- Features Section -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">产品优势</h2>
    </div>
    <div class="col-md-6">
      <ul>
        <li>产品种类齐全</li>
        <li>可靠性高</li>
        <li>良好信誉</li>
        <li>客户认可</li>
        <li>技术人员专业能力强</li>
      </ul>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
    </div>
    <div class="col-md-6"> <img class="img-responsive" src="http://placehold.it/700x450" alt="" /></div>
  </div>
  <!-- /.row -->
  <hr />
  <!-- Call to Action Section -->
  <div class="well">
    <div class="row">
      <div class="col-md-8">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
      </div>
      <div class="col-md-4"> <a class="btn btn-lg btn-default btn-block" href="#">Call to Action</a></div>
    </div>
  </div>
  <?php $this->display('copyright.phtml'); ?>
</div>
<!-- /.container -->
<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
	interval: 5000 //changes the speed
})
</script>
<?php $this->display('footer.phtml'); ?>